# Generated by Django 4.2.16 on 2024-09-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет при отображении'),
        ),
    ]
