# Generated by Django 4.2.16 on 2024-09-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_prior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='priority',
        ),
        migrations.AddField(
            model_name='service',
            name='for_main_page',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной странице'),
        ),
    ]
